language: python

# ensure use container-based infrastructure for caching
sudo: false

python:
#  - "2.6"
  - "2.7"

addons:
  apt:
    packages:
      - oracle-java8-installer

# versions of eXist to test against
env:
#  - EXIST_DB_VERSION=eXist-3.0.RC1
  - EXIST_DB_VERSION=eXist-2.2

before_install:
  - export EXIST_DB_FOLDER=${HOME}/exist/${EXIST_DB_VERSION}
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

install:
  - ci/setup-existdb.sh
  - pip install -e .
  - pip install ".[dev]"
  - pip install coveralls

before_script:
  - ci/start-existdb.sh

script:
  nosetests test/ --with-coverage --cover-package=eulexistdb --cover-xml --with-xunit

after_success:
  - coveralls
  - cd ${EXIST_DB_FOLDER}
  - bin/shutdown.sh


# caching exist to speed up tests
before_cache:
  - ci/teardown-db.sh
cache:
  directories:
    - ${HOME}/exist